{% set name = "s2cloudless" %}
{% set version = "1.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6538894722b7e64d6f79595fa9f4b47ac98523bd323e4a9d918e2920cd438801

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - lightgbm >=2.0.11
    - numpy >=1.13.3
    - python >={{ python_min }}
    - sentinelhub >=3.9.0
    - opencv
    - typing_extensions

test:
  requires:
    - python {{ python_min }}
  imports:
    - s2cloudless

about:
  home: https://github.com/sentinel-hub/sentinel2-cloud-detector
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE.md
  summary: Sentinel Hub's cloud detector for Sentinel-2 imagery
  doc_url: https://pypi.org/project/s2cloudless/

extra:
  recipe-maintainers:
    - batic
    - zigaluksic
    - mxr-conda
    - mwilson8
    - oblute
    - rluria14
    - benhuff
