{% set name = "s2cloudless" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47e8a9031b1cd952c44121402272663f0bf112321ef9301c86ff015f21cb2aa1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - lightgbm >=2.0.11
    - numpy >=1.13.3
    - python >=3.5
    - scikit-image >=0.13.0
    - scipy >=0.19.1
    - sentinelhub >=2.4.6

test:
  imports:
    - s2cloudless

about:
  home: https://github.com/sentinel-hub/sentinel2-cloud-detector
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE.md
  summary: Sentinel Hub's cloud detector for Sentinel-2 imagery
  doc_url: https://pypi.org/project/s2cloudless/

extra:
  recipe-maintainers:
    - batic
    - mxr-conda
    - mwilson8
    - oblute
    - rluria14
    - benhuff
