{% set name = "s2cloudless" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e773dc37ca9c6b9b4e154f05e911ab05f57c33c2fd5425a638050eef540e49c9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
  run:
    - lightgbm >=2.0.11
    - numpy >=1.13.3
    - python >=3.7
    - sentinelhub >=3.9.0
    - opencv
    - typing_extensions

test:
  imports:
    - s2cloudless

about:
  home: https://github.com/sentinel-hub/sentinel2-cloud-detector
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE.md
  summary: Sentinel Hub's cloud detector for Sentinel-2 imagery
  doc_url: https://pypi.org/project/s2cloudless/

extra:
  recipe-maintainers:
    - batic
    - zigaluksic
    - mxr-conda
    - mwilson8
    - oblute
    - rluria14
    - benhuff
